/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Unified API
 * The Unified API description
 * OpenAPI spec version: 1.0
 */
import { customFetch } from './custom-fetch';
export type AuthorizeParams = {
client_id: unknown;
redirect_uri: unknown;
code_challenge?: unknown;
code_challenge_method?: unknown;
state?: unknown;
nonce?: unknown;
login_hint?: unknown;
response_type: unknown;
scope: unknown;
};

export type GetAuthorizeInfoParams = {
client_id: unknown;
redirect_uri: unknown;
code_challenge?: unknown;
code_challenge_method?: unknown;
state?: unknown;
nonce?: unknown;
login_hint?: unknown;
response_type: unknown;
scope: unknown;
};

export type JwksResponseDtoKeysItem = {
  alg: string;
  e: string;
  kid: string;
  kty: string;
  n: string;
  use: string;
};

export interface JwksResponseDto {
  keys: JwksResponseDtoKeysItem[];
}

export interface OpenidConfigurationResponseDto {
  authorization_endpoint: string;
  authorization_signing_alg_values_supported: string[];
  claims_supported: string[];
  code_challenge_methods_supported: string[];
  grant_types_supported: string[];
  id_token_signing_alg_values_supported: string[];
  issuer: string;
  jwks_uri: string;
  prompt_values_supported: string[];
  response_types_supported: string[];
  scopes_supported: string[];
  subject_types_supported: string[];
  token_endpoint: string;
  token_endpoint_auth_methods_supported: string[];
  userinfo_endpoint: string;
}

export interface UserInfoDto {
  email?: string;
  email_verified?: boolean;
  family_name?: string;
  given_name?: string;
  locale?: string;
  name?: string;
  /** @nullable */
  phone?: string | null;
  phone_verified?: boolean;
  /** @nullable */
  picture?: string | null;
  preferred_username?: string;
  scope?: string;
  sub?: string;
  updated_at?: string;
}

export interface ExchangeTokenResponseDto {
  access_token: string;
  expires_in: number;
  id_token?: string;
  refresh_token?: string;
  refresh_token_expires_in?: number;
  scope: string;
  token_type: string;
}

export type AuthorizePostResponseMode = typeof AuthorizePostResponseMode[keyof typeof AuthorizePostResponseMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthorizePostResponseMode = {
  fragment: 'fragment',
  query: 'query',
} as const;

export type AuthorizePostResponseClient = {
  id: string;
};

export interface AuthorizePostResponse {
  client: AuthorizePostResponseClient;
  code: string;
  id_token?: string;
  mode: AuthorizePostResponseMode;
  redirect_uri: string;
  state?: string;
}

export type AuthorizeGetResponseUser = {
  id: string;
  isHinted: boolean;
  login_hint: string;
};

export type AuthorizeGetResponseScopeDetails = {
  extraScopes: string[];
  grantedScopes: string[];
  requestedScopes: string[];
  scopesGranted: boolean;
};

export type AuthorizeGetResponseClient = {
  contactEmail: string;
  enabled?: boolean;
  id: string;
  isAuthorized: boolean;
  name: string;
  picture?: string;
  privacyPolicyUrl?: string;
  termsUrl?: string;
};

export interface AuthorizeGetResponse {
  client: AuthorizeGetResponseClient;
  scopeDetails: AuthorizeGetResponseScopeDetails;
  user: AuthorizeGetResponseUser;
}

export type UpdateClientDtoScopesItem = typeof UpdateClientDtoScopesItem[keyof typeof UpdateClientDtoScopesItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateClientDtoScopesItem = {
  openid: 'openid',
  profile: 'profile',
  email: 'email',
  offline_access: 'offline_access',
} as const;

export interface UpdateClientDto {
  contactEmail?: string;
  name?: string;
  picture?: string;
  privacyPolicyUrl?: string;
  redirectUri?: string[];
  scopes?: UpdateClientDtoScopesItem[];
  termsUrl?: string;
}

export type ClientOkResponseUser = {
  id: string;
};

export interface ClientOkResponse {
  contactEmail: string;
  createdAt: string;
  enabled?: boolean;
  id: string;
  name: string;
  picture?: string;
  privacyPolicyUrl?: string;
  redirectUri: string[];
  scopes: string[];
  termsUrl?: string;
  updatedAt: string;
  user: ClientOkResponseUser;
}

export type ClientOkResponseWithSecretUser = {
  id: string;
};

export interface ClientOkResponseWithSecret {
  contactEmail: string;
  createdAt: string;
  enabled?: boolean;
  id: string;
  name: string;
  picture?: string;
  privacyPolicyUrl?: string;
  redirectUri: string[];
  scopes: string[];
  secret: string;
  termsUrl?: string;
  updatedAt: string;
  user: ClientOkResponseWithSecretUser;
}

export type CreateClientDtoScopesItem = typeof CreateClientDtoScopesItem[keyof typeof CreateClientDtoScopesItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateClientDtoScopesItem = {
  openid: 'openid',
  profile: 'profile',
  email: 'email',
  offline_access: 'offline_access',
} as const;

export interface CreateClientDto {
  contactEmail: string;
  enabled?: boolean;
  name: string;
  picture?: string;
  privacyPolicyUrl?: string;
  redirectUri: string[];
  scopes: CreateClientDtoScopesItem[];
  termsUrl?: string;
}

export type DisableTwoFactorResponseUser = {
  id: string;
};

export interface DisableTwoFactorResponse {
  enabled: boolean;
  user: DisableTwoFactorResponseUser;
}

export type ConfirmTwoFactorResponseUser = {
  id: string;
};

export interface ConfirmTwoFactorResponse {
  enabled: boolean;
  user: ConfirmTwoFactorResponseUser;
}

export interface ConfirmTwoFactorDto {
  code: string;
}

export interface BadRequestException { [key: string]: unknown }

export type EnableTwoFactorResponseUser = {
  id: string;
};

export interface EnableTwoFactorResponse {
  enabled: boolean;
  message: string;
  qrcode: string;
  url: string;
  user: EnableTwoFactorResponseUser;
}

export type GetSignedUrlResponseUser = {
  id: string;
  picture: string;
};

export interface GetSignedUrlResponse {
  expiresIn: string;
  lastModified: string;
  requiredHeaders: string[];
  signedUrl: string;
  user: GetSignedUrlResponseUser;
}

export type UpdatePasswordDtoOtp = {
  /**
   * @minLength 6
   * @maxLength 6
   */
  code: string;
};

export interface UpdatePasswordDto {
  /** @minLength 8 */
  newPassword: string;
  otp?: UpdatePasswordDtoOtp;
  /** @minLength 8 */
  password: string;
  revokeSession?: boolean;
  revokeTrustedDevices?: boolean;
}

export interface ErrorResponseDto {
  error: string;
  message: string;
  statusCode: number;
}

export interface ErrorsObject {
  errors: string;
  message: string;
  path: string;
  requestId: string;
  timestamp: string;
}

export interface HttpExceptionEntity {
  error: ErrorsObject;
  statusCode: number;
}

export type GetAppsResponseDtoItemScopesItem = typeof GetAppsResponseDtoItemScopesItem[keyof typeof GetAppsResponseDtoItemScopesItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAppsResponseDtoItemScopesItem = {
  openid: 'openid',
  profile: 'profile',
  email: 'email',
  offline_access: 'offline_access',
} as const;

export type GetAppsResponseDtoItemClient = {
  contactEmail: string;
  id: string;
  name: string;
  /** @nullable */
  picture: string | null;
};

export type GetAppsResponseDtoItem = {
  client: GetAppsResponseDtoItemClient;
  clientId: string;
  createdAt: string;
  id: string;
  scopes: GetAppsResponseDtoItemScopesItem[];
  updatedAt: string;
  userId: string;
};

export type GetAppsResponseDto = GetAppsResponseDtoItem[];

export type SessionResponseUser = {
  email: string;
  emailVerified: boolean;
  firstName: string;
  id: string;
  lastName: string;
  otp: boolean;
  /** @nullable */
  otpType: string | null;
  /** @nullable */
  picture: string | null;
  username: string;
};

export interface SessionResponse {
  createdAt: unknown;
  expiresAt: unknown;
  id: string;
  requestIp: string;
  user: SessionResponseUser;
  userAgent: string;
  userId: string;
}

export type ContinueLoginDtoOtp = {
  /**
   * @minLength 6
   * @maxLength 6
   */
  code: string;
  type: string;
};

export type ContinueLoginDtoIdentity = {
  email: string;
  /** @minLength 8 */
  password: string;
  trust?: boolean;
};

export interface ContinueLoginDto {
  identity: ContinueLoginDtoIdentity;
  otp: ContinueLoginDtoOtp;
}

export type LoginUser = {
  id: string;
};

export type LoginSession = {
  createdAt: unknown;
  expiresAt: unknown;
  id: string;
  requestIp: string;
  userAgent: string;
  userId: string;
};

export type LoginOtp = {
  required: boolean;
  type?: string;
};

export interface Login {
  otp: LoginOtp;
  session?: LoginSession;
  user: LoginUser;
}

export type LoginUserDtoIdentity = {
  email: string;
  /** @minLength 8 */
  password: string;
  trust?: boolean;
};

export interface LoginUserDto {
  identity: LoginUserDtoIdentity;
}

export type RegisterUser = {
  email: string;
  id: string;
  username: string;
};

export type RegisterSession = {
  createdAt: unknown;
  expiresAt: unknown;
  id: string;
  requestIp: string;
  userAgent: string;
  userId: string;
};

export interface Register {
  session: RegisterSession;
  user: RegisterUser;
}

export interface RegisterUserDto {
  email: string;
  /** @minLength 3 */
  firstName: string;
  /** @minLength 3 */
  lastName: string;
  /** @minLength 8 */
  password: string;
  /** @nullable */
  phone: string | null;
  /**
   * @minLength 3
   * @pattern ^[a-zA-Z0-9]+$
   */
  username: string;
}



export type registerUserResponse = {
  data: Register;
  status: number;
  headers: Headers;
}

export const getRegisterUserUrl = () => {


  return `http://10.1.1.17:3000/v1/identity/register`
}

export const registerUser = async (registerUserDto: RegisterUserDto, options?: RequestInit): Promise<registerUserResponse> => {
  
  return customFetch<Promise<registerUserResponse>>(getRegisterUserUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerUserDto,)
  }
);}



export type logoutUserResponse = {
  data: void;
  status: number;
  headers: Headers;
}

export const getLogoutUserUrl = () => {


  return `http://10.1.1.17:3000/v1/identity/logout`
}

export const logoutUser = async ( options?: RequestInit): Promise<logoutUserResponse> => {
  
  return customFetch<Promise<logoutUserResponse>>(getLogoutUserUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



export type loginUserResponse = {
  data: Login;
  status: number;
  headers: Headers;
}

export const getLoginUserUrl = () => {


  return `http://10.1.1.17:3000/v1/identity/login`
}

export const loginUser = async (loginUserDto: LoginUserDto, options?: RequestInit): Promise<loginUserResponse> => {
  
  return customFetch<Promise<loginUserResponse>>(getLoginUserUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginUserDto,)
  }
);}



export type otpLoginUserResponse = {
  data: Login;
  status: number;
  headers: Headers;
}

export const getOtpLoginUserUrl = () => {


  return `http://10.1.1.17:3000/v1/identity/login/continue`
}

export const otpLoginUser = async (continueLoginDto: ContinueLoginDto, options?: RequestInit): Promise<otpLoginUserResponse> => {
  
  return customFetch<Promise<otpLoginUserResponse>>(getOtpLoginUserUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      continueLoginDto,)
  }
);}



export type getSessionResponse = {
  data: SessionResponse;
  status: number;
  headers: Headers;
}

export const getGetSessionUrl = () => {


  return `http://10.1.1.17:3000/v1/identity/session`
}

export const getSession = async ( options?: RequestInit): Promise<getSessionResponse> => {
  
  return customFetch<Promise<getSessionResponse>>(getGetSessionUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export type getAuthorizedClientsResponse = {
  data: GetAppsResponseDto;
  status: number;
  headers: Headers;
}

export const getGetAuthorizedClientsUrl = () => {


  return `http://10.1.1.17:3000/v1/account/apps`
}

export const getAuthorizedClients = async ( options?: RequestInit): Promise<getAuthorizedClientsResponse> => {
  
  return customFetch<Promise<getAuthorizedClientsResponse>>(getGetAuthorizedClientsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export type revokeClientResponse = {
  data: unknown;
  status: number;
  headers: Headers;
}

export const getRevokeClientUrl = (id: string,) => {


  return `http://10.1.1.17:3000/v1/account/apps/${id}/revoke`
}

export const revokeClient = async (id: string, options?: RequestInit): Promise<revokeClientResponse> => {
  
  return customFetch<Promise<revokeClientResponse>>(getRevokeClientUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



export type updatePasswordResponse = {
  data: unknown;
  status: number;
  headers: Headers;
}

export const getUpdatePasswordUrl = () => {


  return `http://10.1.1.17:3000/v1/account/update-password`
}

export const updatePassword = async (updatePasswordDto: UpdatePasswordDto, options?: RequestInit): Promise<updatePasswordResponse> => {
  
  return customFetch<Promise<updatePasswordResponse>>(getUpdatePasswordUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updatePasswordDto,)
  }
);}



export type getSignedProfilePictureUrlResponse = {
  data: GetSignedUrlResponse;
  status: number;
  headers: Headers;
}

export const getGetSignedProfilePictureUrlUrl = () => {


  return `http://10.1.1.17:3000/v1/account/profile/picture/sign`
}

export const getSignedProfilePictureUrl = async ( options?: RequestInit): Promise<getSignedProfilePictureUrlResponse> => {
  
  return customFetch<Promise<getSignedProfilePictureUrlResponse>>(getGetSignedProfilePictureUrlUrl(),
  {      
    ...options,
    method: 'PUT'
    
    
  }
);}



export type completeProfilePictureUploadResponse = {
  data: unknown;
  status: number;
  headers: Headers;
}

export const getCompleteProfilePictureUploadUrl = () => {


  return `http://10.1.1.17:3000/v1/account/profile/picture/sign/complete`
}

export const completeProfilePictureUpload = async ( options?: RequestInit): Promise<completeProfilePictureUploadResponse> => {
  
  return customFetch<Promise<completeProfilePictureUploadResponse>>(getCompleteProfilePictureUploadUrl(),
  {      
    ...options,
    method: 'PUT'
    
    
  }
);}



export type enableTwoFactorResponse = {
  data: EnableTwoFactorResponse;
  status: number;
  headers: Headers;
}

export const getEnableTwoFactorUrl = () => {


  return `http://10.1.1.17:3000/v1/account/mfa/enable`
}

export const enableTwoFactor = async ( options?: RequestInit): Promise<enableTwoFactorResponse> => {
  
  return customFetch<Promise<enableTwoFactorResponse>>(getEnableTwoFactorUrl(),
  {      
    ...options,
    method: 'PUT'
    
    
  }
);}



export type confirmTwoFactorResponse = {
  data: ConfirmTwoFactorResponse;
  status: number;
  headers: Headers;
}

export const getConfirmTwoFactorUrl = () => {


  return `http://10.1.1.17:3000/v1/account/mfa/enable/confirm`
}

export const confirmTwoFactor = async (confirmTwoFactorDto: ConfirmTwoFactorDto, options?: RequestInit): Promise<confirmTwoFactorResponse> => {
  
  return customFetch<Promise<confirmTwoFactorResponse>>(getConfirmTwoFactorUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      confirmTwoFactorDto,)
  }
);}



export type disableTwoFactorResponse = {
  data: DisableTwoFactorResponse;
  status: number;
  headers: Headers;
}

export const getDisableTwoFactorUrl = () => {


  return `http://10.1.1.17:3000/v1/account/mfa/disable`
}

export const disableTwoFactor = async (confirmTwoFactorDto: ConfirmTwoFactorDto, options?: RequestInit): Promise<disableTwoFactorResponse> => {
  
  return customFetch<Promise<disableTwoFactorResponse>>(getDisableTwoFactorUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      confirmTwoFactorDto,)
  }
);}



export type createClientResponse = {
  data: ClientOkResponseWithSecret;
  status: number;
  headers: Headers;
}

export const getCreateClientUrl = () => {


  return `http://10.1.1.17:3000/v1/clients`
}

export const createClient = async (createClientDto: CreateClientDto, options?: RequestInit): Promise<createClientResponse> => {
  
  return customFetch<Promise<createClientResponse>>(getCreateClientUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createClientDto,)
  }
);}



export type findAllResponse = {
  data: ClientOkResponse[];
  status: number;
  headers: Headers;
}

export const getFindAllUrl = () => {


  return `http://10.1.1.17:3000/v1/clients`
}

export const findAll = async ( options?: RequestInit): Promise<findAllResponse> => {
  
  return customFetch<Promise<findAllResponse>>(getFindAllUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export type renewSecretResponse = {
  data: ClientOkResponseWithSecret;
  status: number;
  headers: Headers;
}

export const getRenewSecretUrl = (id: string,) => {


  return `http://10.1.1.17:3000/v1/clients/secret/renew/${id}`
}

export const renewSecret = async (id: string, options?: RequestInit): Promise<renewSecretResponse> => {
  
  return customFetch<Promise<renewSecretResponse>>(getRenewSecretUrl(id),
  {      
    ...options,
    method: 'PUT'
    
    
  }
);}



export type updateClientResponse = {
  data: ClientOkResponse;
  status: number;
  headers: Headers;
}

export const getUpdateClientUrl = (id: string,) => {


  return `http://10.1.1.17:3000/v1/clients/${id}`
}

export const updateClient = async (id: string,
    updateClientDto: UpdateClientDto, options?: RequestInit): Promise<updateClientResponse> => {
  
  return customFetch<Promise<updateClientResponse>>(getUpdateClientUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateClientDto,)
  }
);}



export type switchClientResponse = {
  data: ClientOkResponse;
  status: number;
  headers: Headers;
}

export const getSwitchClientUrl = (id: string,) => {


  return `http://10.1.1.17:3000/v1/clients/switch/${id}`
}

export const switchClient = async (id: string, options?: RequestInit): Promise<switchClientResponse> => {
  
  return customFetch<Promise<switchClientResponse>>(getSwitchClientUrl(id),
  {      
    ...options,
    method: 'PUT'
    
    
  }
);}



export type getAuthorizeInfoResponse = {
  data: AuthorizeGetResponse;
  status: number;
  headers: Headers;
}

export const getGetAuthorizeInfoUrl = (params: GetAuthorizeInfoParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  return normalizedParams.size ? `http://10.1.1.17:3000/v1/oauth/authorize?${normalizedParams.toString()}` : `http://10.1.1.17:3000/v1/oauth/authorize`
}

export const getAuthorizeInfo = async (params: GetAuthorizeInfoParams, options?: RequestInit): Promise<getAuthorizeInfoResponse> => {
  
  return customFetch<Promise<getAuthorizeInfoResponse>>(getGetAuthorizeInfoUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export type authorizeResponse = {
  data: AuthorizePostResponse;
  status: number;
  headers: Headers;
}

export const getAuthorizeUrl = (params: AuthorizeParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  return normalizedParams.size ? `http://10.1.1.17:3000/v1/oauth/authorize?${normalizedParams.toString()}` : `http://10.1.1.17:3000/v1/oauth/authorize`
}

export const authorize = async (params: AuthorizeParams, options?: RequestInit): Promise<authorizeResponse> => {
  
  return customFetch<Promise<authorizeResponse>>(getAuthorizeUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



export type exchangeTokenResponse = {
  data: ExchangeTokenResponseDto;
  status: number;
  headers: Headers;
}

export const getExchangeTokenUrl = () => {


  return `http://10.1.1.17:3000/v1/oauth/token`
}

export const exchangeToken = async ( options?: RequestInit): Promise<exchangeTokenResponse> => {
  
  return customFetch<Promise<exchangeTokenResponse>>(getExchangeTokenUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



export type testResponse = {
  data: void;
  status: number;
  headers: Headers;
}

export const getTestUrl = () => {


  return `http://10.1.1.17:3000/v1/oauth/token`
}

export const test = async ( options?: RequestInit): Promise<testResponse> => {
  
  return customFetch<Promise<testResponse>>(getTestUrl(),
  {      
    ...options,
    method: 'PUT'
    
    
  }
);}



export type getUserInfoResponse = {
  data: UserInfoDto;
  status: number;
  headers: Headers;
}

export const getGetUserInfoUrl = () => {


  return `http://10.1.1.17:3000/v1/oauth/userinfo`
}

export const getUserInfo = async ( options?: RequestInit): Promise<getUserInfoResponse> => {
  
  return customFetch<Promise<getUserInfoResponse>>(getGetUserInfoUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export type getOpenidConfigurationResponse = {
  data: OpenidConfigurationResponseDto;
  status: number;
  headers: Headers;
}

export const getGetOpenidConfigurationUrl = () => {


  return `http://10.1.1.17:3000/.well-known/openid-configuration`
}

export const getOpenidConfiguration = async ( options?: RequestInit): Promise<getOpenidConfigurationResponse> => {
  
  return customFetch<Promise<getOpenidConfigurationResponse>>(getGetOpenidConfigurationUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export type getJwksResponse = {
  data: JwksResponseDto;
  status: number;
  headers: Headers;
}

export const getGetJwksUrl = () => {


  return `http://10.1.1.17:3000/.well-known/openid-configuration/jwks.json`
}

export const getJwks = async ( options?: RequestInit): Promise<getJwksResponse> => {
  
  return customFetch<Promise<getJwksResponse>>(getGetJwksUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



