---

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_ISSUER_URL=${JWT_ISSUER_URL}
      - JWT_SECRET=${JWT_SECRET}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - CF_EMAIL=${CF_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
      - CF_ZONE_ID=${CF_ZONE_ID}
    ports:
      - "3000:3000"
    depends_on:
      - db

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - BACKEND_URL=${BACKEND_URL}
      - INPUT_FILE_PATH=${INPUT_FILE_PATH}
    ports:
      - "5173:5173"
    depends_on:
      - api

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"