FROM node:21-alpine AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

################################################################################
FROM base AS build

COPY . /usr/src/app
WORKDIR /usr/src/app

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm --filter=./web install --frozen-lockfile
RUN pnpm --filter=./web run build
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm --filter=./web deploy --prod /prod/web
# Copy the dist folder to the deployment directory
RUN cp -r /usr/src/app/web/build /prod/web/

################################################################################
FROM base AS runtime

ENV NODE_ENV=production

COPY --from=build /prod/web/node_modules /prod/web/node_modules
COPY --from=build /prod/web/build /prod/web/build
COPY --from=build /prod/web/package.json /prod/web/package.json

WORKDIR /prod/web
EXPOSE ${PORT} 3000
CMD ["node", "build"]